### ISSUE TITLE
updating the number of available illustrations

### ISSUE THREAD

**Issue by iamtekeste** [AnandChowdhary/undrawcdn#1]
Hey good job with this free api. As of today your api returns around 439 illustrations whereas unDraw has passed 800 total illustrations. 
Do you think you would get a chance to add the new illustrations? If you show me the way I can even do it myself and send you a pull request.

Thank you!

**Comment by AnandChowdhary** [comment]
Hi @iamtekeste, I'll update the illustrations. The end goal here is to automate this process (right now I manually crawl the site, copy paste the source code, parse all images, and download and add them to the repo).

**Comment by iamtekeste** [comment]
Thanks for the reply @AnandChowdhary unfortunately the makers of unDraw told me I can't use your CDN because it violates their license.

**Comment by AnandChowdhary** [comment]
Undraw illustrations, including all the ones in this repository, were originally MIT licensed. This means that I (was) free to make this CDN/API service.

However, in light of their new license, which makes the illustrations open source but doesn't allow compilation and scraping, I'm retiring this service.
